services:
  # Backend Service
  - type: web
    name: intervue-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        fromService:
          type: web
          name: intervue-frontend
          property: host

  # Frontend Service  
  - type: web
    name: intervue-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html